#import "SettingsController.h"
#import "Brand.h"
@interface NotesController : UIViewController
@end
@implementation NotesController { UITextView *_notes; }
- (void)viewDidLoad {
 [super viewDidLoad];self.title=@"Saved memory";self.view.backgroundColor=NABackground();
 UILabel *hint=[UILabel new];hint.text=@"Add facts or preferences you want Next AI to use in future chats. Only notes you save here are remembered across chats. Up to 1,000 characters.";hint.numberOfLines=0;hint.font=[UIFont preferredFontForTextStyle:UIFontTextStyleSubheadline];hint.textColor=UIColor.secondaryLabelColor;
 _notes=[UITextView new];_notes.font=[UIFont preferredFontForTextStyle:UIFontTextStyleBody];_notes.backgroundColor=UIColor.secondarySystemGroupedBackgroundColor;_notes.layer.cornerRadius=18;_notes.textContainerInset=UIEdgeInsetsMake(16,12,16,12);_notes.text=[NSUserDefaults.standardUserDefaults stringForKey:@"memoryNotes"] ?: @"";
 UIStackView *s=[[UIStackView alloc] initWithArrangedSubviews:@[hint,_notes]];s.axis=UILayoutConstraintAxisVertical;s.spacing=18;s.translatesAutoresizingMaskIntoConstraints=NO;[self.view addSubview:s];[NSLayoutConstraint activateConstraints:@[[s.topAnchor constraintEqualToAnchor:self.view.safeAreaLayoutGuide.topAnchor constant:20],[s.leadingAnchor constraintEqualToAnchor:self.view.leadingAnchor constant:20],[s.trailingAnchor constraintEqualToAnchor:self.view.trailingAnchor constant:-20],[s.bottomAnchor constraintEqualToAnchor:self.view.keyboardLayoutGuide.topAnchor constant:-20]]];self.navigationItem.rightBarButtonItem=[[UIBarButtonItem alloc] initWithTitle:@"Save" style:UIBarButtonItemStyleDone target:self action:@selector(save)];
}
- (void)save {if(_notes.text.length>1000){UIAlertController *a=[UIAlertController alertControllerWithTitle:@"Shorten your notes" message:@"Memory supports up to 1,000 characters so there is room for your conversation." preferredStyle:UIAlertControllerStyleAlert];[a addAction:[UIAlertAction actionWithTitle:@"OK" style:UIAlertActionStyleDefault handler:nil]];[self presentViewController:a animated:YES completion:nil];return;}[NSUserDefaults.standardUserDefaults setObject:_notes.text forKey:@"memoryNotes"];[self.navigationController popViewControllerAnimated:YES];}
@end
@implementation SettingsController
- (instancetype)init {return [super initWithStyle:UITableViewStyleInsetGrouped];}
- (void)viewDidLoad {[super viewDidLoad];self.title=@"Settings";self.tableView.backgroundColor=NABackground();
 UIView *header=[[UIView alloc] initWithFrame:CGRectMake(0,0,320,180)];UIImageView *icon=[[UIImageView alloc] initWithImage:[UIImage imageNamed:@"NextAI-Icon"]];icon.translatesAutoresizingMaskIntoConstraints=NO;icon.layer.cornerRadius=22;icon.clipsToBounds=YES;[header addSubview:icon];UILabel *name=[UILabel new];name.text=@"NEXT AI  /  NEXT JAILBREAK";name.font=[UIFont systemFontOfSize:12 weight:UIFontWeightSemibold];name.textColor=NAAccent();name.translatesAutoresizingMaskIntoConstraints=NO;[header addSubview:name];[NSLayoutConstraint activateConstraints:@[[icon.centerXAnchor constraintEqualToAnchor:header.centerXAnchor],[icon.topAnchor constraintEqualToAnchor:header.topAnchor constant:16],[icon.widthAnchor constraintEqualToConstant:96],[icon.heightAnchor constraintEqualToConstant:96],[name.centerXAnchor constraintEqualToAnchor:header.centerXAnchor],[name.topAnchor constraintEqualToAnchor:icon.bottomAnchor constant:16]]];self.tableView.tableHeaderView=header;
}
- (void)viewWillAppear:(BOOL)animated {[super viewWillAppear:animated];[self.tableView reloadData];}
- (NSInteger)numberOfSectionsInTableView:(UITableView *)table {return 5;}
- (NSInteger)tableView:(UITableView *)t numberOfRowsInSection:(NSInteger)s {return s==0?3:(s==1?2:(s==2?1:(s==3?3:3)));}
- (NSString *)tableView:(UITableView *)t titleForHeaderInSection:(NSInteger)s {return @[@"Memory",@"Conversations",@"Appearance",@"Model downloads",@"Next AI · 1.0"] [s];}
- (NSString *)tableView:(UITableView *)t titleForFooterInSection:(NSInteger)s {return s==0?@"Memory stays on this iPhone. Switching it off stops including your notes in new replies; Clear saved memory deletes the notes. The model may not follow every preference.":(s==1?@"Saving off creates temporary chats and stops future conversation saves. Previously saved chats remain available. No automatic uploads; device backups may include app data.":(s==3?@"Downloads open in your browser. Finish downloading, then import the GGUF in Chat or Create. Models are separate downloads with their own licenses.":nil));}
- (UITableViewCell *)tableView:(UITableView *)t cellForRowAtIndexPath:(NSIndexPath *)p {
 UITableViewCell *c=[[UITableViewCell alloc] initWithStyle:UITableViewCellStyleSubtitle reuseIdentifier:nil];c.textLabel.numberOfLines=0;c.detailTextLabel.numberOfLines=0;c.backgroundColor=UIColor.secondarySystemGroupedBackgroundColor;
 NSArray *titles=@[@[@"Remember across chats",@"Edit saved memory",@"Clear saved memory"],@[@"Save conversations",@"Resume last chat"],@[@"Theme"],@[@"Chat · Qwen 1.5B",@"Fast images · SD-Turbo",@"Standard images · SD 1.5"],@[@"About & credits",@"Open Next Jailbreak",@"Open-source licenses"]];c.textLabel.text=titles[p.section][p.row];
 if((p.section==0 && p.row==0)||p.section==1){NSArray *keys=p.section==0?@[@"memoryEnabled"]:@[@"saveChats",@"resumeChat"];UISwitch *sw=[UISwitch new];sw.onTintColor=NAAccent();sw.accessibilityLabel=c.textLabel.text;sw.accessibilityIdentifier=keys[p.row];sw.on=[NSUserDefaults.standardUserDefaults boolForKey:keys[p.row]];[sw addTarget:self action:@selector(toggle:) forControlEvents:UIControlEventValueChanged];c.accessoryView=sw;c.selectionStyle=UITableViewCellSelectionStyleNone;}
 else {c.accessoryType=UITableViewCellAccessoryDisclosureIndicator;}
 if(p.section==0&&p.row==1)c.detailTextLabel.text=[NSString stringWithFormat:@"%lu / 1,000 characters",(unsigned long)[[NSUserDefaults.standardUserDefaults stringForKey:@"memoryNotes"] length]];
 if(p.section==0&&p.row==2)c.textLabel.textColor=UIColor.systemRedColor;
 if(p.section==2)c.detailTextLabel.text=@[@"System",@"Light",@"Dark"] [MIN(2,MAX(0,[NSUserDefaults.standardUserDefaults integerForKey:@"appearance"]))];
 return c;
}
- (void)toggle:(UISwitch *)s {[NSUserDefaults.standardUserDefaults setBool:s.on forKey:s.accessibilityIdentifier];[NSNotificationCenter.defaultCenter postNotificationName:@"NASettingsChanged" object:nil];}
- (void)showText:(NSString *)text title:(NSString *)title {UIViewController *v=[UIViewController new];v.title=title;UITextView *view=[UITextView new];view.editable=NO;view.font=[UIFont preferredFontForTextStyle:UIFontTextStyleBody];view.text=text;view.backgroundColor=NABackground();view.textContainerInset=UIEdgeInsetsMake(24,20,24,20);v.view=view;[self.navigationController pushViewController:v animated:YES];}
- (void)tableView:(UITableView *)t didSelectRowAtIndexPath:(NSIndexPath *)p {
 [t deselectRowAtIndexPath:p animated:YES];NSUserDefaults *d=NSUserDefaults.standardUserDefaults;
 if(p.section==0&&p.row==1){[self.navigationController pushViewController:[NotesController new] animated:YES];return;}
 if(p.section==0&&p.row==2){UIAlertController *a=[UIAlertController alertControllerWithTitle:@"Clear saved memory?" message:@"This permanently removes your saved notes. Your conversations are kept." preferredStyle:UIAlertControllerStyleAlert];[a addAction:[UIAlertAction actionWithTitle:@"Cancel" style:UIAlertActionStyleCancel handler:nil]];[a addAction:[UIAlertAction actionWithTitle:@"Clear memory" style:UIAlertActionStyleDestructive handler:^(UIAlertAction *x){[d removeObjectForKey:@"memoryNotes"];[self.tableView reloadData];}]];[self presentViewController:a animated:YES completion:nil];}
 if(p.section==2){UIAlertController *a=[UIAlertController alertControllerWithTitle:@"Appearance" message:nil preferredStyle:UIAlertControllerStyleActionSheet];NSArray *names=@[@"System",@"Light",@"Dark"];for(NSInteger i=0;i<3;i++)[a addAction:[UIAlertAction actionWithTitle:names[i] style:UIAlertActionStyleDefault handler:^(UIAlertAction *x){[d setInteger:i forKey:@"appearance"];NAApplyTheme(self.view.window);[self.tableView reloadData];}]];[a addAction:[UIAlertAction actionWithTitle:@"Cancel" style:UIAlertActionStyleCancel handler:nil]];a.popoverPresentationController.sourceView=[t cellForRowAtIndexPath:p];a.popoverPresentationController.sourceRect=[t cellForRowAtIndexPath:p].bounds;[self presentViewController:a animated:YES completion:nil];}
 if(p.section==3){NSArray *urls=@[@"https://huggingface.co/Qwen/Qwen2.5-1.5B-Instruct-GGUF",@"https://huggingface.co/gpustack/stable-diffusion-v2-1-turbo-GGUF",@"https://huggingface.co/second-state/stable-diffusion-v1-5-GGUF"];[UIApplication.sharedApplication openURL:[NSURL URLWithString:urls[p.row]] options:@{} completionHandler:nil];}
 if(p.section==4&&p.row==0)[self showText:@"NEXT AI\nYour ideas. On your iPhone.\n\nCreated by Zeeshan Barvi\nA Next Jailbreak application\nnextjailbreak.com · @nextjailbreak\n\nOffline chat, optional saved memory and image generation. No account or cloud inference required. Models are downloaded separately.\n\nPowered by llama.cpp and stable-diffusion.cpp with GGML and Apple Metal. Chat model by Qwen; image models by Stability AI. GGUF conversions distributed by their respective maintainers.\n\nAI answers and images can be inaccurate. Saved memory is limited context, not model training.\n\niOS 16+ · TrollStore build\nVersion 1.0.0" title:@"About & credits"];
 if(p.section==4&&p.row==1)[UIApplication.sharedApplication openURL:[NSURL URLWithString:@"https://nextjailbreak.com"] options:@{} completionHandler:nil];
 if(p.section==4&&p.row==2){NSMutableString *text=[NSMutableString new];for(NSString *name in @[@"llama-LICENSE",@"stable-diffusion-LICENSE",@"photo-ggml-LICENSE"]){NSString *s=[NSString stringWithContentsOfFile:[NSBundle.mainBundle pathForResource:name ofType:@"txt"] encoding:NSUTF8StringEncoding error:nil];[text appendFormat:@"%@\n\n%@\n\n",name,s ?: @"License file unavailable."];}[self showText:text title:@"Open-source licenses"];}
}
@end
